version: "3.9"

services:
  redis:
    image: redis:7
    container_name: nodeA-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --bind 0.0.0.0 --protected-mode no

  product-pu:
    build: ./product-pu
    container_name: nodeA-product-pu
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: nodeA-frontend
    ports:
      - "3000:80"
    depends_on:
      - product-pu
