version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app_net

  web:
    build: .
    container_name: django-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app_net

  worker:
    build: .
    container_name: celery-worker
    command: celery -A app worker --loglevel=info
    depends_on:
      - redis
    networks:
      - app_net

networks:
  app_net: